### ISSUE TITLE
v2021.2.0 build fails on Ubuntu 18.04 with gcc-10.3.0

### ISSUE THREAD

**Issue by pauljurczak** [oneapi-src/oneTBB#386]
I'm building v2021.2.0 branch on Ubuntu 18.04 with gcc-10.3.0 and it fails with this error message:
```
[100%] Linking CXX executable ../gnu_10.3_cxx11_64_release/test_malloc_atexit
[100%] Built target test_malloc_atexit
In file included from /home/paul/intel/oneTBB/src/tbb/../../include/oneapi/tbb/concurrent_queue.h:21,
                 from /home/paul/intel/oneTBB/test/conformance/conformance_concurrent_queue.cpp:24:
/home/paul/intel/oneTBB/src/tbb/../../include/oneapi/tbb/detail/_concurrent_queue_base.h: In function ‘void TestConstructors() [with CQ = ConcQWithSizeWrapper<Bar>; T = Bar; TIter = BarIterator; CQ_EX = ConcQWithSizeWrapper<BarEx>; T_EX = BarEx]’:
/home/paul/intel/oneTBB/src/tbb/../../include/oneapi/tbb/detail/_concurrent_queue_base.h:547:29: error: ‘dqb_ex.tbb::detail::d1::concurrent_queue_iterator_base<BarEx, tbb::detail::d1::cache_aligned_allocator<BarEx> >::my_array[7]’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
  547 |                 my_array[i] = other.my_array[i];
      |                 ~~~~~~~~~~~~^~~~~~~~~~~~~~~~~
compilation terminated due to -Wfatal-errors.
cc1plus: all warnings being treated as errors
test/CMakeFiles/conformance_concurrent_queue.dir/build.make:81: recipe for target 'test/CMakeFiles/conformance_concurrent_queue.dir/conformance/conformance_concurrent_queue.cpp.o' failed
make[2]: *** [test/CMakeFiles/conformance_concurrent_queue.dir/conformance/conformance_concurrent_queue.cpp.o] Error 1
CMakeFiles/Makefile2:3348: recipe for target 'test/CMakeFiles/conformance_concurrent_queue.dir/all' failed
make[1]: *** [test/CMakeFiles/conformance_concurrent_queue.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[100%] Linking CXX executable ../gnu_10.3_cxx11_64_release/test_intrusive_list
[100%] Built target test_intrusive_list
[100%] Linking CXX executable ../gnu_10.3_cxx11_64_release/conformance_enumerable_thread_specific
[100%] Built target conformance_enumerable_thread_specific
Makefile:181: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by pauljurczak** [comment]
I'm getting the same error with master branch:
```
[ 44%] Building CXX object test/CMakeFiles/test_environment_whitebox.dir/tbb/test_environment_whitebox.cpp.o
In file included from /home/paul/intel/oneTBB/src/tbb/../../include/oneapi/tbb/concurrent_queue.h:21,
                 from /home/paul/intel/oneTBB/test/conformance/conformance_concurrent_queue.cpp:24:
/home/paul/intel/oneTBB/src/tbb/../../include/oneapi/tbb/detail/_concurrent_queue_base.h: In function ‘void TestConstructors() [with CQ = ConcQWithSizeWrapper<Bar>; T = Bar; TIter = BarIterator; CQ_EX = ConcQWithSizeWrapper<BarEx>; T_EX = BarEx]’:
/home/paul/intel/oneTBB/src/tbb/../../include/oneapi/tbb/detail/_concurrent_queue_base.h:547:29: error: ‘dqb_ex.tbb::detail::d1::concurrent_queue_iterator_base<BarEx, tbb::detail::d1::cache_aligned_allocator<BarEx> >::my_array[7]’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
  547 |                 my_array[i] = other.my_array[i];
      |                 ~~~~~~~~~~~~^~~~~~~~~~~~~~~~~
compilation terminated due to -Wfatal-errors.
cc1plus: all warnings being treated as errors
test/CMakeFiles/conformance_concurrent_queue.dir/build.make:81: recipe for target 'test/CMakeFiles/conformance_concurrent_queue.dir/conformance/conformance_concurrent_queue.cpp.o' failed
make[2]: *** [test/CMakeFiles/conformance_concurrent_queue.dir/conformance/conformance_concurrent_queue.cpp.o] Error 1
CMakeFiles/Makefile2:3458: recipe for target 'test/CMakeFiles/conformance_concurrent_queue.dir/all' failed
make[1]: *** [test/CMakeFiles/conformance_concurrent_queue.dir/all] Error 2
```

**Comment by alexey-katranov** [comment]
Thank you for the report. The issue will be fixed in one of future releases.

**Comment by gbschenkel** [comment]
Getting error on test_malloc_overload.cpp

```
$ make 
[  9%] Built target tbb
[ 11%] Built target tbbmalloc
[ 12%] Built target tbbmalloc_proxy
[ 13%] Building CXX object test/CMakeFiles/test_malloc_new_handler.dir/tbbmalloc/test_malloc_new_handler.cpp.o
[ 13%] Linking CXX executable ../gnu_10.3_cxx11_64_release/test_malloc_new_handler
[ 13%] Built target test_malloc_new_handler
[ 13%] Building CXX object test/CMakeFiles/test_malloc_overload_disable.dir/tbbmalloc/test_malloc_overload_disable.cpp.o
[ 13%] Linking CXX executable ../gnu_10.3_cxx11_64_release/test_malloc_overload_disable
[ 13%] Built target test_malloc_overload_disable
[ 13%] Building CXX object test/CMakeFiles/test_malloc_overload.dir/tbbmalloc/test_malloc_overload.cpp.o
/home/schenkel/Development/git/slackbuilds/libraries/tbb/oneTBB-2021.2.0/test/tbbmalloc/test_malloc_overload.cpp: In function ‘void _DOCTEST_ANON_FUNC_39()’:
/home/schenkel/Development/git/slackbuilds/libraries/tbb/oneTBB-2021.2.0/test/tbbmalloc/test_malloc_overload.cpp:437:37: error: ‘mallinfo mallinfo()’ is deprecated [-Werror=deprecated-declarations]
  437 |     struct mallinfo info = mallinfo();
      |                                     ^
compilation terminated due to -Wfatal-errors.
cc1plus: all warnings being treated as errors
make[2]: *** [test/CMakeFiles/test_malloc_overload.dir/build.make:76: test/CMakeFiles/test_malloc_overload.dir/tbbmalloc/test_malloc_overload.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:582: test/CMakeFiles/test_malloc_overload.dir/all] Error 2
make: *** [Makefile:166: all] Error 2
```

**Comment by vlserov** [comment]
Build failure with 'mallinfo()' has been resolved with PR #433.
Initial issue has been fixed with [commit ](https://github.com/oneapi-src/oneTBB/commit/478de5b1887c928e52f029d706af6ea640a877be#diff-39e4acc7b239a4903473b1f141a1cf12c7686d200891271fd6c22cce344ae97aL591-R591).

```diff
-padded_page* my_array[queue_rep_type::n_queue];
+padded_page* my_array[queue_rep_type::n_queue]{};
```

**Comment by vlserov** [comment]
Resolved with [v2021.4.0](/oneapi-src/oneTBB/releases/tag/v2021.4.0) release.
