### ISSUE TITLE
2021.2.0: build fails

### ISSUE THREAD

**Issue by kloczek** [oneapi-src/oneTBB#370]
```
make  -f src/tbb/CMakeFiles/tbb.dir/build.make src/tbb/CMakeFiles/tbb.dir/depend
make[2]: Entering directory '/home/tkloczko/rpmbuild/BUILD/oneTBB-2021.2.0/x86_64-redhat-linux-gnu'
cd /home/tkloczko/rpmbuild/BUILD/oneTBB-2021.2.0/x86_64-redhat-linux-gnu && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /home/tkloczko/rpmbuild/BUILD/oneTBB-2021.2.0 /home/tkloczko/rpmbuild/BUILD/oneTBB-2021.2.0/src/tbb /home/tkloczko/rpmbuild/BUILD/oneTBB-2021.2.0/x86_64-redhat-linux-gnu /home/tkloczko/rpmbuild/BUILD/oneTBB-2021.2.0/x86_64-redhat-linux-gnu/src/tbb /home/tkloczko/rpmbuild/BUILD/oneTBB-2021.2.0/x86_64-redhat-linux-gnu/src/tbb/CMakeFiles/tbb.dir/DependInfo.cmake --color=
make[2]: Leaving directory '/home/tkloczko/rpmbuild/BUILD/oneTBB-2021.2.0/x86_64-redhat-linux-gnu'
make  -f src/tbb/CMakeFiles/tbb.dir/build.make src/tbb/CMakeFiles/tbb.dir/build
make[2]: Entering directory '/home/tkloczko/rpmbuild/BUILD/oneTBB-2021.2.0/x86_64-redhat-linux-gnu'
[  0%] Building CXX object src/tbb/CMakeFiles/tbb.dir/arena.cpp.o
cd /home/tkloczko/rpmbuild/BUILD/oneTBB-2021.2.0/x86_64-redhat-linux-gnu/src/tbb && /usr/bin/g++ -D__TBB_BUILD -D__TBB_USE_ITT_NOTIFY -I/home/tkloczko/rpmbuild/BUILD/oneTBB-2021.2.0/src/tbb/../../include -O2 -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fdata-sections -ffunction-sections -flto=auto -flto-partition=none -DNDEBUG -fPIC -MMD -flifetime-dse=1 -Wall -Wextra -Werror -Wfatal-errors -mrtm -pthread -std=c++11 -o CMakeFiles/tbb.dir/arena.cpp.o -c /home/tkloczko/rpmbuild/BUILD/oneTBB-2021.2.0/src/tbb/arena.cpp
In file included from /usr/lib/gcc/x86_64-redhat-linux/11/include/x86gprintrin.h:81,
                 from /usr/lib/gcc/x86_64-redhat-linux/11/include/immintrin.h:27,
                 from /home/tkloczko/rpmbuild/BUILD/oneTBB-2021.2.0/src/tbb/../../include/oneapi/tbb/detail/_machine.h:33,
                 from /home/tkloczko/rpmbuild/BUILD/oneTBB-2021.2.0/src/tbb/../../include/oneapi/tbb/detail/_utils.h:26,
                 from /home/tkloczko/rpmbuild/BUILD/oneTBB-2021.2.0/src/tbb/task_dispatcher.h:20,
                 from /home/tkloczko/rpmbuild/BUILD/oneTBB-2021.2.0/src/tbb/arena.cpp:17:
/home/tkloczko/rpmbuild/BUILD/oneTBB-2021.2.0/src/tbb/scheduler_common.h: In function ‘tbb::detail::r1::prolonged_pause()’:
/usr/lib/gcc/x86_64-redhat-linux/11/include/waitpkgintrin.h:53:1: error: inlining failed in call to ‘always_inline’ ‘_tpause(unsigned int, unsigned long long)’: target specific option mismatch
   53 | _tpause (unsigned int __A, unsigned long long __B)
      | ^~~~~~~
compilation terminated due to -Wfatal-errors.
make[2]: *** [src/tbb/CMakeFiles/tbb.dir/build.make:98: src/tbb/CMakeFiles/tbb.dir/arena.cpp.o] Error 1
```

**Comment by isaevil** [comment]
@kloczek This issue will be fixed in the next release or update of the master branch.

**Comment by kloczek** [comment]
> I totally forgot to mention that the error occurs on 32-bit only. Sorry about that.

In my case build fails on x86_64.

**Comment by isaevil** [comment]
@kloczek Is your case relevant for 2021.2 or 2021.4?

**Comment by kloczek** [comment]
Just started testing 2021.4.0 and found that build is now OK.
Closing.

Thank you :)

**Comment by kloczek** [comment]
cmake 3.21.3 and here is set on cmake parames which I'm using (from script generated by rpmbuild):
```console
+ /usr/bin/cmake -B x86_64-redhat-linux-gnu -D BUILD_SHARED_LIBS=ON -D CMAKE_AR=/usr/bin/gcc-ar -D CMAKE_BUILD_TYPE=RelWithDebInfo -D CMAKE_C_FLAGS_RELEASE=-DNDEBUG -D CMAKE_CXX_FLAGS_RELEASE=-DNDEBUG -D CMAKE_Fortran_FLAGS_RELEASE=-DNDEBUG -D CMAKE_INSTALL_PREFIX=/usr -D CMAKE_NM=/usr/bin/gcc-nm -D CMAKE_RANLIB=/usr/bin/gcc-ranlib -D CMAKE_VERBOSE_MAKEFILE=ON -D DBUILD_SHARED_LIBS=ON -D INCLUDE_INSTALL_DIR=/usr/include -D LIB_INSTALL_DIR=/usr/lib64 -D LIB_SUFFIX=64 -D SHARE_INSTALL_PREFIX=/usr/share -D SYSCONF_INSTALL_DIR=/etc -S . -D TBB4PY_BUILD=ON -D TBB_EXAMPLES=ON -D TBB_TEST=ON -D TBB_TEST_SPEC=ON
```

**Comment by detrout** [comment]
Hi,

We at Debian tried building 2021.05.0 and are experiencing this error on the i386 architecture.

```
FAILED: src/tbb/CMakeFiles/tbb.dir/arena.cpp.o 
/usr/bin/c++ -D__TBB_BUILD -D__TBB_USE_ITT_NOTIFY -I/<<PKGBUILDDIR>>/src/tbb/../../include -g -O2 -ffile-prefix-map=/<<PKGBUILDDIR>>=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -flifetime-dse=1 -Wall -Wextra -Werror -Wfatal-errors -flto -pthread -std=c++11 -MD -MT src/tbb/CMakeFiles/tbb.dir/arena.cpp.o -MF src/tbb/CMakeFiles/tbb.dir/arena.cpp.o.d -o src/tbb/CMakeFiles/tbb.dir/arena.cpp.o -c /<<PKGBUILDDIR>>/src/tbb/arena.cpp
In file included from /usr/lib/gcc/i686-linux-gnu/11/include/x86gprintrin.h:89,
                 from /usr/lib/gcc/i686-linux-gnu/11/include/immintrin.h:27,
                 from /<<PKGBUILDDIR>>/src/tbb/../../include/oneapi/tbb/detail/_machine.h:42,
                 from /<<PKGBUILDDIR>>/src/tbb/../../include/oneapi/tbb/detail/_utils.h:26,
                 from /<<PKGBUILDDIR>>/src/tbb/task_dispatcher.h:20,
                 from /<<PKGBUILDDIR>>/src/tbb/arena.cpp:17:
/<<PKGBUILDDIR>>/src/tbb/scheduler_common.h: In function ‘tbb::detail::r1::prolonged_pause()’:
/usr/lib/gcc/i686-linux-gnu/11/include/waitpkgintrin.h:53:1: error: inlining failed in call to ‘always_inline’ ‘_tpause(unsigned int, unsigned long long)’: target specific option mismatch
   53 | _tpause (unsigned int __A, unsigned long long __B)
      | ^~~~~~~
compilation terminated due to -Wfatal-errors.
```

Our full build log is available here:
https://buildd.debian.org/status/fetch.php?pkg=onetbb&arch=i386&ver=2021.5.0-1&stamp=1643933756&raw=0

We were using gcc 11.2.0 with cmake 3.22.1 targeting the ninja system.

**Comment by isaevil** [comment]
@detrout, this error was fixed by https://github.com/oneapi-src/oneTBB/pull/609 but it didn't come to 2021.5. Please expect this fix in one of future releases.

**Comment by detrout** [comment]
Thank you for the link to the patch! and the information that it hasn't been released yet.

**Comment by higaski** [comment]
Still happening on my system with 9d2a3477ce276d437bf34b1582781e5b11f9b37a and x86_64

```
FAILED: _deps/onetbb-build/src/tbb/CMakeFiles/tbb.dir/arena.cpp.obj 
/usr/bin/x86_64-w64-mingw32-g++ -D__TBB_BUILD -D__TBB_USE_ITT_NOTIFY -I/home/vinci/Develop/VSCode/BiQuadSim/build/_deps/onetbb-build/src/tbb/tbb_autogen/include -I/home/vinci/Develop/VSCode/BiQuadSim/build/_deps/onetbb-src/src/tbb/../../include -static-libstdc++ -O3 -g -flto -fno-fat-lto-objects -flifetime-dse=1 -Wall -Wextra -Werror -Wfatal-errors -std=c++11 -MD -MT _deps/onetbb-build/src/tbb/CMakeFiles/tbb.dir/arena.cpp.obj -MF _deps/onetbb-build/src/tbb/CMakeFiles/tbb.dir/arena.cpp.obj.d -o _deps/onetbb-build/src/tbb/CMakeFiles/tbb.dir/arena.cpp.obj -c /home/vinci/Develop/VSCode/BiQuadSim/build/_deps/onetbb-src/src/tbb/arena.cpp
In file included from /usr/lib/gcc/x86_64-w64-mingw32/11.2.0/include/x86gprintrin.h:81,
                 from /usr/lib/gcc/x86_64-w64-mingw32/11.2.0/include/x86intrin.h:27,
                 from /usr/x86_64-w64-mingw32/include/intrin.h:69,
                 from /home/vinci/Develop/VSCode/BiQuadSim/build/_deps/onetbb-src/src/tbb/../../include/oneapi/tbb/detail/_machine.h:29,
                 from /home/vinci/Develop/VSCode/BiQuadSim/build/_deps/onetbb-src/src/tbb/../../include/oneapi/tbb/detail/_utils.h:26,
                 from /home/vinci/Develop/VSCode/BiQuadSim/build/_deps/onetbb-src/src/tbb/task_dispatcher.h:20,
                 from /home/vinci/Develop/VSCode/BiQuadSim/build/_deps/onetbb-src/src/tbb/arena.cpp:17:
/home/vinci/Develop/VSCode/BiQuadSim/build/_deps/onetbb-src/src/tbb/scheduler_common.h: In function ‘tbb::detail::r1::prolonged_pause()’:
/usr/lib/gcc/x86_64-w64-mingw32/11.2.0/include/waitpkgintrin.h:53:1: error: inlining failed in call to ‘always_inline’ ‘_tpause’: target specific option mismatch
   53 | _tpause (unsigned int __A, unsigned long long __B)
      | ^~~~~~~
compilation terminated due to -Wfatal-errors.
ninja: build stopped: subcommand failed.
```

**Comment by isaevil** [comment]
@higaski could you please share some info about your environment (like build cmd)? I have tried to build with MinGW GCC 11.2.1 on Fedora 35 and there were no issues.

**Comment by higaski** [comment]
I've added oneTBB to my project using CMake's [FetchContent](https://cmake.org/cmake/help/latest/module/FetchContent.html) module. I haven't changed any options at all. I'm also not passing anything to CMake besides my toolchain file which points to the MinGW C and C++ compiler executables.

MinGW GCC version installed is 11.2.0 from ARCH AUR.

**Comment by isaevil** [comment]
@higaski absence of -mwaitpkg option is the reason of compile error. There is a check in [GNU.cmake](https://github.com/oneapi-src/oneTBB/blob/master/cmake/compilers/GNU.cmake):
```CMake
if (CMAKE_SYSTEM_PROCESSOR MATCHES "(AMD64|amd64|i.86|x86)")
    set(TBB_COMMON_COMPILE_FLAGS ${TBB_COMMON_COMPILE_FLAGS} -mrtm $<$<AND:$<NOT:$<CXX_COMPILER_ID:Intel>>,$<NOT:$<VERSION_LESS:${CMAKE_CXX_COMPILER_VERSION},11.0>>>:-mwaitpkg>)
endif()
```
And it was expected that if gcc >= 11 the option would be inserted for x86 systems. What does `message(${CMAKE_SYSTEM_PROCESSOR})` say on yours?

**Comment by higaski** [comment]
> @higaski absence of -mwaitpkg option is the reason of compile error. There is a check in [GNU.cmake](https://github.com/oneapi-src/oneTBB/blob/master/cmake/compilers/GNU.cmake):

Yeah I got that, but I thought my processor would surely fall into any of the "AMD64" categories...

> 
> And it was expected that if gcc >= 11 the option would be inserted for x86 systems. What does `message(${CMAKE_SYSTEM_PROCESSOR})` say on yours?

... which apparently it doesn't. `CMAKE_SYSTEM_PROCESSOR` is empty on my system.

**Comment by kloczek** [comment]
Just tested 2021.5.0 and build still fail (but other way)
```console
[  9%] Building CXX object test/CMakeFiles/test_tick_count.dir/tbb/test_tick_count.cpp.o
cd /home/tkloczko/rpmbuild/BUILD/oneTBB-2021.5.0/x86_64-redhat-linux-gnu/test && /usr/bin/g++  -I/home/tkloczko/rpmbuild/BUILD/oneTBB-2021.5.0/test/.. -I/home/tkloczko/rpmbuild/BUILD/oneTBB-2021.5.0/test -I/home/tkloczko/rpmbuild/BUILD/oneTBB-2021.5.0/src/tbb/../../include -O2 -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fdata-sections -ffunction-sections -flto=auto -flto-partition=none -DNDEBUG -Wall -Wextra -Werror -Wfatal-errors -Wshadow -Wcast-qual -Woverloaded-virtual -Wnon-virtual-dtor -mrtm -mwaitpkg -std=c++11 -MD -MT test/CMakeFiles/test_tick_count.dir/tbb/test_tick_count.cpp.o -MF CMakeFiles/test_tick_count.dir/tbb/test_tick_count.cpp.o.d -o CMakeFiles/test_tick_count.dir/tbb/test_tick_count.cpp.o -c /home/tkloczko/rpmbuild/BUILD/oneTBB-2021.5.0/test/tbb/test_tick_count.cpp
In file included from /home/tkloczko/rpmbuild/BUILD/oneTBB-2021.5.0/src/tbb/../../include/oneapi/tbb/concurrent_vector.h:24,
                 from /home/tkloczko/rpmbuild/BUILD/oneTBB-2021.5.0/src/tbb/../../include/oneapi/tbb/enumerable_thread_specific.h:26,
                 from /home/tkloczko/rpmbuild/BUILD/oneTBB-2021.5.0/test/common/utils_concurrency_limit.h:25,
                 from /home/tkloczko/rpmbuild/BUILD/oneTBB-2021.5.0/test/tbb/test_tick_count.cpp:19:
/home/tkloczko/rpmbuild/BUILD/oneTBB-2021.5.0/src/tbb/../../include/oneapi/tbb/detail/_segment_table.h: In instantiation of ‘tbb::detail::d1::segment_table<T, Allocator, DerivedType, PointersPerEmbeddedTable>::segment_table(const allocator_type&) [with T = tbb::detail::d0::padded<tbb::detail::d1::ets_element<bool>, 128>; Allocator = tbb::detail::d1::cache_aligned_allocator<tbb::detail::d0::padded<tbb::detail::d1::ets_element<bool>, 128> >; DerivedType = tbb::detail::d1::concurrent_vector<tbb::detail::d0::padded<tbb::detail::d1::ets_element<bool>, 128>, tbb::detail::d1::cache_aligned_allocator<tbb::detail::d0::padded<tbb::detail::d1::ets_element<bool>, 128> > >; long unsigned int PointersPerEmbeddedTable = 3; allocator_type = tbb::detail::d1::cache_aligned_allocator<tbb::detail::d0::padded<tbb::detail::d1::ets_element<bool>, 128> >]’:
/home/tkloczko/rpmbuild/BUILD/oneTBB-2021.5.0/src/tbb/../../include/oneapi/tbb/concurrent_vector.h:284:26:   required from ‘tbb::detail::d1::concurrent_vector<T, Allocator>::concurrent_vector(const allocator_type&) [with T = tbb::detail::d0::padded<tbb::detail::d1::ets_element<bool>, 128>; Allocator = tbb::detail::d1::cache_aligned_allocator<tbb::detail::d0::padded<tbb::detail::d1::ets_element<bool>, 128> >; allocator_type = tbb::detail::d1::cache_aligned_allocator<tbb::detail::d0::padded<tbb::detail::d1::ets_element<bool>, 128> >]’
/home/tkloczko/rpmbuild/BUILD/oneTBB-2021.5.0/src/tbb/../../include/oneapi/tbb/concurrent_vector.h:281:61:   required from ‘tbb::detail::d1::concurrent_vector<T, Allocator>::concurrent_vector() [with T = tbb::detail::d0::padded<tbb::detail::d1::ets_element<bool>, 128>; Allocator = tbb::detail::d1::cache_aligned_allocator<tbb::detail::d0::padded<tbb::detail::d1::ets_element<bool>, 128> >]’
/home/tkloczko/rpmbuild/BUILD/oneTBB-2021.5.0/src/tbb/../../include/oneapi/tbb/enumerable_thread_specific.h:843:5:   required from ‘tbb::detail::d1::enumerable_thread_specific<T, Allocator, ETS_key_type>::enumerable_thread_specific() [with T = bool; Allocator = tbb::detail::d1::cache_aligned_allocator<bool>; tbb::detail::d1::ets_key_usage_type ETS_key_type = tbb::detail::d1::ets_no_key]’
/home/tkloczko/rpmbuild/BUILD/oneTBB-2021.5.0/test/common/utils_concurrency_limit.h:248:92:   required from here
/home/tkloczko/rpmbuild/BUILD/oneTBB-2021.5.0/src/tbb/../../include/oneapi/tbb/detail/_segment_table.h:63:63: error: member ‘tbb::detail::d1::segment_table<tbb::detail::d0::padded<tbb::detail::d1::ets_element<bool>, 128>, tbb::detail::d1::cache_aligned_allocator<tbb::detail::d0::padded<tbb::detail::d1::ets_element<bool>, 128> >, tbb::detail::d1::concurrent_vector<tbb::detail::d0::padded<tbb::detail::d1::ets_element<bool>, 128>, tbb::detail::d1::cache_aligned_allocator<tbb::detail::d0::padded<tbb::detail::d1::ets_element<bool>, 128> > >, 3>::my_embedded_table’ is used uninitialized [-Werror=uninitialized]
   63 |         : my_segment_table_allocator(alloc), my_segment_table(my_embedded_table)
      |                                                               ^~~~~~~~~~~~~~~~~
compilation terminated due to -Wfatal-errors.
cc1plus: all warnings being treated as errors
````
cmake settings:
```console
[tkloczko@devel-g2v x86_64-redhat-linux-gnu]$ cmake -L
CMake Warning:
  No source or binary directory provided.  Both will be assumed to be the
  same as the current working directory, but note that this warning will
  become a fatal error in future CMake releases.


CMake Error: The source directory "/home/tkloczko/rpmbuild/BUILD/oneTBB-2021.5.0/x86_64-redhat-linux-gnu" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.
-- Cache values
CMAKE_BUILD_TYPE:STRING=RelWithDebInfo
CMAKE_INSTALL_PREFIX:PATH=/usr
EXAMPLES_UI_MODE:STRING=con
MKL_CORE_LIB:FILEPATH=MKL_CORE_LIB-NOTFOUND
MKL_INTEL_LP64_LIB:FILEPATH=MKL_INTEL_LP64_LIB-NOTFOUND
MKL_SEQUENTIAL_LIB:FILEPATH=MKL_SEQUENTIAL_LIB-NOTFOUND
SDE_EXE:FILEPATH=SDE_EXE-NOTFOUND
TACHYON_VERSION:STRING=tbb
TBB4PY_BUILD:BOOL=ON
TBBMALLOC_BUILD:BOOL=ON
TBB_BUILD:BOOL=ON
TBB_CPF:BOOL=OFF
TBB_DISABLE_HWLOC_AUTOMATIC_SEARCH:BOOL=OFF
TBB_EXAMPLES:BOOL=ON
TBB_FIND_PACKAGE:BOOL=OFF
TBB_INSTALL_VARS:BOOL=OFF
TBB_NO_APPCONTAINER:BOOL=OFF
TBB_SANITIZE:STRING=
TBB_STRICT:BOOL=ON
TBB_TEST:BOOL=ON
TBB_TEST_SPEC:BOOL=ON
TBB_VALGRIND_MEMCHECK:BOOL=OFF
TBB_WINDOWS_DRIVER:BOOL=OFF
```

**Comment by fake-name** [comment]
This is still occurring both on HEAD and tags/v2021.5.0

```
durr@rosbox18:/opt/workspace/libraries/tbb/build$ make
[  0%] Linking CXX shared library ../../gnu_11.1_cxx11_64_relwithdebinfo/libtbb.so
/tmp/ccuWCMIH.s: Assembler messages:
/tmp/ccuWCMIH.s:39021: Error: no such instruction: `tpause %ecx'
lto-wrapper: fatal error: /usr/bin/c++ returned 1 exit status
compilation terminated.
/usr/bin/ld: error: lto-wrapper failed
collect2: error: ld returned 1 exit status
src/tbb/CMakeFiles/tbb.dir/build.make:529: recipe for target 'gnu_11.1_cxx11_64_relwithdebinfo/libtbb.so.12.5' failed
make[2]: *** [gnu_11.1_cxx11_64_relwithdebinfo/libtbb.so.12.5] Error 1
CMakeFiles/Makefile2:458: recipe for target 'src/tbb/CMakeFiles/tbb.dir/all' failed
make[1]: *** [src/tbb/CMakeFiles/tbb.dir/all] Error 2
Makefile:165: recipe for target 'all' failed
make: *** [all] Error 2

```

``
durr@rosbox18:/opt/workspace/libraries/tbb/build$ gcc --version
gcc (Ubuntu 11.1.0-1ubuntu1~18.04.1) 11.1.0
Copyright (C) 2021 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

durr@rosbox18:/opt/workspace/libraries/tbb/build$ uname -a
Linux rosbox18 4.15.0-171-generic #180-Ubuntu SMP Wed Mar 2 17:25:05 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

```

**Comment by fake-name** [comment]
Looking further, it seems like this might be a gcc-11 issue.

The compilation step that's failing is:
```
/usr/bin/c++ -fPIC -march=native -mtune=native -mwaitpkg -mrtm -O3 -DNDEBUG -Wl,--version-script=/opt/workspace/libraries/tbb/src/tbb/def/lin64-tbb.def -flto -mwaitpkg -mrtm -shared -Wl,-soname,libtbb.so.12 -o ../../gnu_11.1_cxx11_64_release/libtbb.so.12.5 CMakeFiles/tbb.dir/address_waiter.cpp.o CMakeFiles/tbb.dir/allocator.cpp.o CMakeFiles/tbb.dir/arena.cpp.o CMakeFiles/tbb.dir/arena_slot.cpp.o CMakeFiles/tbb.dir/concurrent_bounded_queue.cpp.o CMakeFiles/tbb.dir/dynamic_link.cpp.o CMakeFiles/tbb.dir/exception.cpp.o CMakeFiles/tbb.dir/governor.cpp.o CMakeFiles/tbb.dir/global_control.cpp.o CMakeFiles/tbb.dir/itt_notify.cpp.o CMakeFiles/tbb.dir/main.cpp.o CMakeFiles/tbb.dir/market.cpp.o CMakeFiles/tbb.dir/misc.cpp.o CMakeFiles/tbb.dir/misc_ex.cpp.o CMakeFiles/tbb.dir/observer_proxy.cpp.o CMakeFiles/tbb.dir/parallel_pipeline.cpp.o CMakeFiles/tbb.dir/private_server.cpp.o CMakeFiles/tbb.dir/profiling.cpp.o CMakeFiles/tbb.dir/rml_tbb.cpp.o CMakeFiles/tbb.dir/rtm_mutex.cpp.o CMakeFiles/tbb.dir/rtm_rw_mutex.cpp.o CMakeFiles/tbb.dir/semaphore.cpp.o CMakeFiles/tbb.dir/small_object_pool.cpp.o CMakeFiles/tbb.dir/task.cpp.o CMakeFiles/tbb.dir/task_dispatcher.cpp.o CMakeFiles/tbb.dir/task_group_context.cpp.o CMakeFiles/tbb.dir/version.cpp.o CMakeFiles/tbb.dir/queuing_rw_mutex.cpp.o  -ldl -pthread
```

Inserting newlines, you get:

```
/usr/bin/c++ 
-fPIC 
-march=native 
-mtune=native 
-mwaitpkg 
-mrtm 
-O3 
-DNDEBUG 
-Wl,--version-script=/opt/workspace/libraries/tbb/src/tbb/def/lin64-tbb.def 
-flto 
-mwaitpkg 
-mrtm 
-shared 
-Wl,-soname,libtbb.so.12 
-o 
../../gnu_11.1_cxx11_64_release/libtbb.so.12.5 
CMakeFiles/tbb.dir/address_waiter.cpp.o 
CMakeFiles/tbb.dir/allocator.cpp.o 
CMakeFiles/tbb.dir/arena.cpp.o 
CMakeFiles/tbb.dir/arena_slot.cpp.o 
CMakeFiles/tbb.dir/concurrent_bounded_queue.cpp.o 
CMakeFiles/tbb.dir/dynamic_link.cpp.o 
CMakeFiles/tbb.dir/exception.cpp.o 
CMakeFiles/tbb.dir/governor.cpp.o 
CMakeFiles/tbb.dir/global_control.cpp.o 
CMakeFiles/tbb.dir/itt_notify.cpp.o 
CMakeFiles/tbb.dir/main.cpp.o 
CMakeFiles/tbb.dir/market.cpp.o 
CMakeFiles/tbb.dir/misc.cpp.o 
CMakeFiles/tbb.dir/misc_ex.cpp.o 
CMakeFiles/tbb.dir/observer_proxy.cpp.o 
CMakeFiles/tbb.dir/parallel_pipeline.cpp.o 
CMakeFiles/tbb.dir/private_server.cpp.o 
CMakeFiles/tbb.dir/profiling.cpp.o 
CMakeFiles/tbb.dir/rml_tbb.cpp.o 
CMakeFiles/tbb.dir/rtm_mutex.cpp.o 
CMakeFiles/tbb.dir/rtm_rw_mutex.cpp.o 
CMakeFiles/tbb.dir/semaphore.cpp.o 
CMakeFiles/tbb.dir/small_object_pool.cpp.o 
CMakeFiles/tbb.dir/task.cpp.o 
CMakeFiles/tbb.dir/task_dispatcher.cpp.o 
CMakeFiles/tbb.dir/task_group_context.cpp.o 
CMakeFiles/tbb.dir/version.cpp.o 
CMakeFiles/tbb.dir/queuing_rw_mutex.cpp.o 
-ldl 
-pthread
```

So it's being passed both `-mwaitpkg` and `-mrtm`, but some part of the LTO process is failing.

**Comment by ionenwks** [comment]
> ```
> /tmp/ccuWCMIH.s: Assembler messages:
> /tmp/ccuWCMIH.s:39021: Error: no such instruction: `tpause %ecx'
> lto-wrapper: fatal error: /usr/bin/c++ returned 1 exit status
> ```

Seen someone else run into this and thought I'd mention that this is due to your binutils being too old. Haven't checked exact minimum version for assembler tpause support, but user had this failing with binutils-2.29.1, worked when they upgraded to 2.37.

**Comment by kloczek** [comment]
> Seen someone else run into this and thought I'd mention that this is due to your binutils being too old. Haven't checked exact minimum version for assembler tpause support, but user had this failing with binutils-2.29.1, worked when they upgraded to 2.37.

I'm using binutils 2.38.

**Comment by ionenwks** [comment]
> I'm using binutils 2.38.

Yours was a different issue, was replying to this comment: https://github.com/oneapi-src/oneTBB/issues/370#issuecomment-1091104929

**Comment by fake-name** [comment]
Hmm, it is slightly different. 

I'm going to have whichever binutils you get on ubuntu 18.04 lts. For the moment, I just reverted to gcc 10.

**Comment by fake-name** [comment]
Circling back to this, I'm using binutils 2.30-21ubuntu1~18.04.7.

**Comment by rheavr** [comment]
Has there ever been a resolution or workaround to building TBB with GCC11?

**Comment by isaevil** [comment]
@rheavr I would kindly ask you to create a separate issue with description of your problem with details (your system and environment, what kind of problem with building you are actually facing, what version of `oneTBB`). It can be not related with the original problem of this closed issue.

**Comment by fake-name** [comment]
As far as I know, this is still a problem.

I solved it by just pinning GCC10, since I needed to make things work (this is a transitive dependency in a project I'm working on). I don't have the time to debug further.
