### ISSUE TITLE
Build fails on FreeBSD (13.0)

### ISSUE THREAD

**Issue by emaste** [oneapi-src/oneTBB#408]
```
FAILED: test/CMakeFiles/conformance_blocked_range2d.dir/conformance/conformance_blocked_range2d.cpp.o 
/usr/bin/c++  -I../test/.. -I../test -I../src/tbb/../../include -O2 -g -DNDEBUG -Wall -Wextra -Werror -Wshadow -Wcast-qual -Woverloaded-virtual -Wnon-virtual-dtor -pthread -std=c++11 -MD -MT test/CMakeFiles/conformance_blocked_range2d.dir/conformance/conformance_blocked_range2d.cpp.o -MF test/CMakeFiles/conformance_blocked_range2d.dir/conformance/conformance_blocked_range2d.cpp.o.d -o test/CMakeFiles/conformance_blocked_range2d.dir/conformance/conformance_blocked_range2d.cpp.o -c ../test/conformance/conformance_blocked_range2d.cpp
In file included from ../test/conformance/conformance_blocked_range2d.cpp:20:
../test/common/utils_concurrency_limit.h:173:5: error: unknown type name 'cpu_set_t'; did you mean 'cpuset_t'?
    cpu_set_t* mask = nullptr;
    ^~~~~~~~~
    cpuset_t
/usr/include/sys/_cpuset.h:50:24: note: 'cpuset_t' declared here
typedef struct _cpuset cpuset_t;
                       ^
In file included from ../test/conformance/conformance_blocked_range2d.cpp:20:
../test/common/utils_concurrency_limit.h:174:20: error: unknown type name 'cpu_set_t'; did you mean 'cpuset_t'?
    ncpus = sizeof(cpu_set_t) * CHAR_BIT;
                   ^~~~~~~~~
                   cpuset_t
```

Appears to be introduced in 4523a7615eaed49c4ed75654b349ca41b92c6381

**Comment by ivankochin** [comment]
Hi @emaste,
Could you please try out the following solution: https://github.com/oneapi-src/oneTBB/tree/fix-freebsd-testing ?

**Comment by emaste** [comment]
Thanks, it resolves that error. Now getting this error:
```
In file included from ../test/conformance/conformance_global_control.cpp:20:
../test/common/utils_concurrency_limit.h:182:16: error: use of undeclared identifier 'CPU_ALLOC'
        mask = CPU_ALLOC(ncpus);
               ^
../test/common/utils_concurrency_limit.h:184:29: error: use of undeclared identifier 'CPU_ALLOC_SIZE'
        const size_t size = CPU_ALLOC_SIZE(ncpus);
                            ^
../test/common/utils_concurrency_limit.h:185:9: error: use of undeclared identifier 'CPU_ZERO_S'
        CPU_ZERO_S(size, mask);
        ^
../test/common/utils_concurrency_limit.h:186:25: error: use of undeclared identifier 'sched_getaffinity'
        const int err = sched_getaffinity(0, size, mask);
                        ^
../test/common/utils_concurrency_limit.h:189:9: error: use of undeclared identifier 'CPU_FREE'
        CPU_FREE(mask);
        ^
../test/common/utils_concurrency_limit.h:196:25: error: use of undeclared identifier 'CPU_ALLOC_SIZE'
    const size_t size = CPU_ALLOC_SIZE(ncpus);
                        ^
../test/common/utils_concurrency_limit.h:197:26: error: use of undeclared identifier 'CPU_COUNT_S'
    const int num_cpus = CPU_COUNT_S(size, mask);
                         ^
../test/common/utils_concurrency_limit.h:199:13: error: use of undeclared identifier 'CPU_ISSET_S'
        if (CPU_ISSET_S(i, size, mask)) {
            ^
../test/common/utils_concurrency_limit.h:204:5: error: use of undeclared identifier 'CPU_FREE'
    CPU_FREE(mask);
    ^
../test/common/utils_concurrency_limit.h:208:25: error: use of undeclared identifier 'CPU_ALLOC_SIZE'
    const size_t size = CPU_ALLOC_SIZE(ncpus);
                        ^
../test/common/utils_concurrency_limit.h:213:27: error: use of undeclared identifier 'CPU_ALLOC'
    mask_t *target_mask = CPU_ALLOC(ncpus);
                          ^
../test/common/utils_concurrency_limit.h:215:5: error: use of undeclared identifier 'CPU_ZERO_S'
    CPU_ZERO_S(size, target_mask);
    ^
../test/common/utils_concurrency_limit.h:216:5: error: use of undeclared identifier 'CPU_SET_S'
    CPU_SET_S(mapped_idx, size, target_mask);
    ^
../test/common/utils_concurrency_limit.h:217:21: error: use of undeclared identifier 'sched_setaffinity'
    const int err = sched_setaffinity(0, size, target_mask);
                    ^
../test/common/utils_concurrency_limit.h:220:5: error: use of undeclared identifier 'CPU_FREE'
    CPU_FREE(target_mask);
    ^
15 errors generated.
```

and if I ignore that, one more:
```
[  3%] Linking CXX shared library ../../clang_11.0_cxx11_64_relwithdebinfo/libtbbbind_2_4.so
ld: error: cannot open /usr/local/lib: Is a directory
ld: error: unable to find library -lhwloc
c++: error: linker command failed with exit code 1 (use -v to see invocation)
gmake[2]: *** [src/tbbbind/CMakeFiles/tbbbind_2_4.dir/build.make:98: clang_11.0_cxx11_64_relwithdebinfo/libtbbbind_2_4.so.3.3] Error 1
```

I'm not sure where in the CMake this comes from, but it looks like we're passing hwloc's lib dir (just `/usr/local/lib`) rather than the linker flag (`-L/usr/local/lib`)

**Comment by ivankochin** [comment]
@emaste, I have updated the branch with a new patch, could you please check it one more time?

**Comment by emaste** [comment]
That one is fixed. The hwloc linking error remains, and now this one:

```
FAILED: test/CMakeFiles/test_malloc_compliance.dir/tbbmalloc/test_malloc_compliance.cpp.o 
/usr/bin/c++  -I../test/.. -I../test -I../src/tbbmalloc/../../include -O2 -g -DNDEBUG -Wall -Wextra -Werror -Wshadow -Wcast-qual -Woverloaded-virtual -Wnon-virtual-dtor -pthread -std=c++11 -MD -MT test/CMakeFiles/test_malloc_compliance.dir/tbbmalloc/test_malloc_compliance.cpp.o -MF test/CMakeFiles/test_malloc_compliance.dir/tbbmalloc/test_malloc_compliance.cpp.o.d -o test/CMakeFiles/test_malloc_compliance.dir/tbbmalloc/test_malloc_compliance.cpp.o -c ../test/tbbmalloc/test_malloc_compliance.cpp
../test/tbbmalloc/test_malloc_compliance.cpp:94:45: error: comparison of integers of different signs: 'size_t' (aka 'unsigned long') and 'rlim_t' (aka 'long') [-Werror,-Wsign-compare]
    else rlim.rlim_cur = (limit > 0 && limit<rlim.rlim_max) ? limit*MByte : rlim.rlim_max;
                                       ~~~~~^~~~~~~~~~~~~~
```

**Comment by emaste** [comment]
I added a cast in test_malloc_compliance.cpp and edited build.ninja to adjust the hwloc link lines and the build finished.

**Comment by ivankochin** [comment]
I created the MR(#425) with the fix for FreeBSD. Could you please clarify how do you update the `test_malloc_compliance` to fix compilation?

Regards the linking with the HWLOC library. This library is required for the `TBBBind` library building. The `TBBbind` library is a library that helps TBB to parse system topology and provides information for the `tbb::info` related interfaces, but you may delete it and all will work fine. The absence of the TBBbind library causes only filling `tbb::info` interfaces by stubs and the absence of pinning during the passing of `tbb::task_arena::constraints` to the `tbb::task_arena`. ([additional_information1](https://spec.oneapi.com/versions/latest/elements/oneTBB/source/task_scheduler/task_arena/task_arena_cls.html#_CPPv410task_arena11constraintsj8priority), [additional_information2](https://spec.oneapi.com/versions/latest/elements/oneTBB/source/info_namespace.html))

By default, the suitable HWLOC version is searched on the system using the `PkgConfig` Cmake module, but this way doesn't work on FreeBSD you may specify paths to the library using the special variables during CMake build or disable the TBBbind library build using `TBB_TBBBIND_BUILD` CMake option that was added in patch mentioned above [[additional_information3](https://github.com/oneapi-src/oneTBB/blob/7146351f412a7e537edfe475605bcb590d11b4b5/cmake/README.md#tbbbind-library-configuration)].

**Comment by emaste** [comment]
> Could you please clarify how do you update the test_malloc_compliance to fix compilation?

I did this:
```
diff --git a/test/tbbmalloc/test_malloc_compliance.cpp b/test/tbbmalloc/test_malloc_compliance.cpp
index 1fb2586b..e7bef29a 100644
--- a/test/tbbmalloc/test_malloc_compliance.cpp
+++ b/test/tbbmalloc/test_malloc_compliance.cpp
@@ -91,7 +91,7 @@ void limitMem( size_t limit )
     }
     if (rlim.rlim_max==(rlim_t)RLIM_INFINITY)
         rlim.rlim_cur = (limit > 0) ? limit*MByte : rlim.rlim_max;
-    else rlim.rlim_cur = (limit > 0 && limit<rlim.rlim_max) ? limit*MByte : rlim.rlim_max;
+    else rlim.rlim_cur = (limit > 0 && (long)limit<rlim.rlim_max) ? limit*MByte : rlim.rlim_max;
     ret = setrlimit(RLIMIT_AS,&rlim);
     if (0 != ret) {
         REPORT("Can't set limits: errno %d\n", errno);
```
but this might not be right or might regress Linux; I will consider it more.

**Comment by ivankochin** [comment]
I updated the MR by the fix for the `test_malloc_compliance`.

Could you please test the latest MR(#425) state and confirm that it solves all issues mentioned above?

**Comment by ivankochin** [comment]
The corresponding fix was successfully merged to master after validation, so I close the issue. Please reopen the issue, if it wasn't fixed.
